### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by weirongting** [xinyu198736/Rabbit.js#3]
第一次使用，执行 rabbit create 报错，Error: Failed to lookup view "502.jade" in views directory "undefined/views/" ，不知道哪里出了问题， 启动后，访问首页面，提示异常
Express
500 Error: Failed to lookup view "502.jade" in views directory "undefined/views/"
at Function.app.render (G:\hello\node_modules\express\lib\application.js:493:17)
at ServerResponse.res.render (G:\hello\node_modules\express\lib\response.js:798:7)
at Object.handle (G:\hello\rabbit\ExpressInit.js:54:24)
at IncomingMessage.next (G:\hello\node_modules\express\node_modules\connect\lib\proto.js:188:17)
at fn (G:\hello\node_modules\express\lib\response.js:793:25)
at Function.app.render (G:\hello\node_modules\express\lib\application.js:495:14)
at ServerResponse.res.render (G:\hello\node_modules\express\lib\response.js:798:7)
at G:\hello\rabbit\ExpressInit.js:49:24
at callbacks (G:\hello\node_modules\express\lib\router\index.js:164:37)
at param (G:\hello\node_modules\express\lib\router\index.js:138:11)

**Comment by jinlzhang** [comment]
同样报错
